on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc libcurl4-openssl-dev libcjson-dev dpkg-dev

      - name: Set version from tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Build binary
        run: gcc aslookup.c -o aslookup -lcurl -lcjson -lresolv

      - name: Prepare .deb package structure
        run: |
          mkdir -p pkg/usr/local/bin
          cp aslookup pkg/usr/local/bin/
          mkdir -p pkg/DEBIAN
          cat <<EOF > pkg/DEBIAN/control
          Package: aslookup
          Version: ${RELEASE_VERSION}
          Section: utils
          Priority: optional
          Architecture: amd64
          Maintainer: Niel Nielsen <nieldk@gmail.com>
          Description: ASN lookup utility
          Depends: libc6, libcurl4, libcjson1
          EOF

      - name: Build .deb package
        run: dpkg-deb --build pkg aslookup_${RELEASE_VERSION}_amd64.deb

      - name: Upload .deb to release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: aslookup_${{ env.RELEASE_VERSION }}_amd64.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }
