name: Build and Release aslookup-win on Windows

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install MinGW
        run: choco install mingw -y

      - name: Add MinGW to PATH
        run: echo "C:\Program Files\mingw-w64\x86_64-12.2.0-posix-seh-rt_v10-rev2\mingw64\bin" >> $GITHUB_PATH

      - name: Download libcurl for Windows
        run: curl -LO --ssl-no-revoke https://curl.se/windows/dl-8.7.1_2/curl-8.7.1_2-win64-mingw.zip

      - name: Extract libcurl ZIP
        run: powershell -Command "Expand-Archive -Path curl-8.7.1_2-win64-mingw.zip -DestinationPath ."

      - name: Build aslookup-win.exe
        run: gcc aslookup-win.c cJSON.c -o aslookup-win.exe -I. -I./curl-8.7.1_2-win64-mingw/include -L./curl-8.7.1_2-win64-mingw/lib -lcurl -lws2_32

      - name: Set release version
        run: echo "RELEASE_VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV

      - name: Package executable and DLL
        run: |
          powershell -Command "Copy-Item -Path ./curl-8.7.1_2-win64-mingw/bin/libcurl-x64.dll -Destination ./libcurl-x64.dll"
          powershell -Command "Compress-Archive -Path aslookup-win.exe, libcurl-x64.dll -DestinationPath aslookup_${{ env.RELEASE_VERSION }}_win.zip"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: aslookup_${{ env.RELEASE_VERSION }}_win.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
