name: Build and Release aslookup-win on Windows

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install MinGW
        run: choco install mingw -y

      - name: Add MinGW to PATH
        run: echo "C:\Program Files\mingw-w64\x86_64-12.2.0-posix-seh-rt_v10-rev2\mingw64\bin" >> $GITHUB_PATH

      - name: Download libcurl for Windows
        run: curl -LO https://curl.se/windows/dl-8.7.1_2/curl-8.7.1_2-win64-mingw.zip

      - name: Extract libcurl ZIP
        run: powershell -Command "Expand-Archive -Path curl-8.7.1_2-win64-mingw.zip -DestinationPath ."

      - name: Build aslookup-win.exe
        run: gcc aslookup-win.c cJSON.c -o aslookup-win.exe -I. -I./curl-8.7.1_2-win64-mingw/include -L./curl-8.7.1_2-win64-mingw/lib -lcurl -lws2_32

      - name: Package executable and DLL
        run: |
          copy ./curl-8.7.1_2-win64-mingw/bin/libcurl.dll .
          powershell -Command "Compress-Archive -Path aslookup-win.exe, libcurl.dll -DestinationPath aslookup-win.zip"

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./aslookup-win.zip
          asset_name: aslookup-win.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
