name: Build and Release aslookup

on:
  push:
    tags:
      - 'v*'  # Only run on version tags

jobs:
  build-and-release:
    runs-on: windows-latest

    env:
      EXE_NAME: aslookup.exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install dependencies
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat
          .\vcpkg\vcpkg.exe install curl cjson

      - name: Compile aslookup.c
        run: |
          cl aslookup.c /I.\vcpkg\installed\x64-windows\include /link /LIBPATH:.\vcpkg\installed\x64-windows\lib /out:${{ env.EXE_NAME }}

      - name: Create Release and Upload Artifact
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.EXE_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
